---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages("ggpattern")
rm(list=ls())
library(tidyverse)
```

```{r}
data <- read_csv(file = "out.csv")
data <- data[data$Model=="Relative",]

df1 <- data
df2 <- data

df1$y <- df1$b1
df1$Condition <- "Item"
df2$y <- df2$b1 + df2$b2
df2$Condition <- "Bundle"

pdata <- bind_rows(df1, df2)
voi <- c("Subject", "Mask", "Condition", "y")
pdata <- pdata[,voi]
pdata$Condition <- factor(pdata$Condition, levels=c("Item","Bundle"))

pdata$group <- ""
pdata$group[pdata$Mask=="vmPFC" & pdata$Condition==1] = "vmPFC-Item"
pdata$group[pdata$Mask=="vmPFC" & pdata$Condition==2] = "vmPFC-Bundle"
pdata$group[pdata$Mask=="OFCmed" & pdata$Condition==1] = "mOFC-Item"
pdata$group[pdata$Mask=="OFCmed" & pdata$Condition==2] = "mOFC-Bundle"
pdata$group[pdata$Mask=="dmPFC" & pdata$Condition==1] = "dmPFC-Item"
pdata$group[pdata$Mask=="dmPFC" & pdata$Condition==2] = "dmPFC-Bundle"

pdata$group <- factor(
  pdata$group,
  levels = c("vmPFC-Item","mOFC-Item","dmPFC-Item","vmPFC-Bundle","mOFC-Bundle","dmPFC-Bundle"),
  labels = c("vmPFC-Item","mOFC-Item","dmPFC-Item","vmPFC-Bundle","mOFC-Bundle","dmPFC-Bundle")
)

bundle_coeff <- pdata %>% filter(Condition == 'Bundle') %>% pull(y) %>% mean()
bundle_se <- pdata %>% filter(Condition == 'Bundle') %>% pull(y) %>% mean()/sqrt(14)
item_coeff <- pdata %>% filter(Condition == 'Item') %>% pull(y) %>% mean()
item_se <- pdata %>% filter(Condition == 'Item') %>% pull(y) %>% mean()/sqrt(14)

```

```{r}
vmPFC_color = "#66c2a6"
mOFC_color =  "#fc8d62"
dmPFC_color = "#8ea0cb"
fills <- c(
  "vmPFC" = vmPFC_color,
  "OFCmed" = mOFC_color,
  "dmPFC" = dmPFC_color
)

alpha_item = 0.33
alpha_bundle = 1.0
alphas <- c(
  "Item" = alpha_item,
  "Bundle" = alpha_bundle
)

p <-ggplot(data=pdata, aes(x = Subject, y = y)) +
  theme_bw() +
  geom_vline(xintercept = seq(101.5, 113.5, by = 1), color = "grey70") +
  geom_hline(yintercept = 0, color="grey70") +
  
  geom_bar(stat="identity", aes(alpha=Condition, fill=Mask), position="dodge") +
  
  geom_hline(yintercept = item_coeff, color="grey70", linetype=2,) +
  geom_ribbon(aes(ymin=item_coeff-item_se, ymax=item_coeff+item_se), linetype=2, alpha=0.11)+
  geom_hline(yintercept = bundle_coeff, color="black", linetype=2,) +
  geom_ribbon(aes(ymin=bundle_coeff-bundle_se, ymax=bundle_coeff+bundle_se), linetype=2, alpha=0.5)+
  
  labs(title = "", y = "RSA Value Coefficient", x = "Subject", fill = "ROI", alpha="Condition") +
  coord_cartesian(ylim=c(-8,16), xlim=c(100.5, 114.5), expand=F) +
  scale_fill_manual(values=fills) +
  scale_alpha_manual(values=alphas) +
  scale_x_continuous(breaks=c(101:114)) +
  scale_y_continuous(breaks=seq(-6,16,2), labels=c("-6","-4","-2","0","2","4","6","8","10","12","14",">16")) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank()
  )

plot(p)
ggsave("out.pdf", plot=p)
```



